# Tweepy analysis

In [1]:
import datetime
import time

import tweepy
import pandas as pd
import numpy as np

consumer_key = 'XXXXXX'
consumer_secret = 'XXXXXX'
access_token = 'XXXXXX'
access_token_secret = 'XXXXXX'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

In [6]:
df = pd.read_csv('twitter_account_verified_final.csv')
df['twitter'] = df.twitter.str.extract('twitter.com/(.*)')
df.head()

,district,name,party,state,twitter,url,district_N
0,"Candidate, U.S. House Alabama District 6",Danner Kline,Democratic,Alabama,votedannerkline,https://ballotpedia.org/Danner_Kline,6
1,"Candidate, U.S. House Alabama District 4",Lee Auman,Democratic,Alabama,LeeAuman2018,https://ballotpedia.org/Lee_Auman,4
2,"Candidate, U.S. House Alabama District 3",Mallory Hagan,Democratic,Alabama,HaganforHouse,https://ballotpedia.org/Mallory_Hagan,3
3,"Candidate, U.S. House Alabama District 5",Peter Joffrion,Democratic,Alabama,peter_joffrion,https://ballotpedia.org/Peter_Joffrion,5
4,"Candidate, U.S. House Alabama District 1",Robert Kennedy Jr.,Democratic,Alabama,Kennedy4Alabama,https://ballotpedia.org/Robert_Kennedy_Jr._(Al...,1

In [7]:
len(df)

677

In [8]:
tweet_df = pd.DataFrame(columns=['created_at','retweet_count','favorite_count','text','name','party'])

In [9]:
for i in range(0,len(df)):
    tweet = []
    for status in tweepy.Cursor(api.user_timeline, screen_name='@'+df.twitter[i]).items():
        tweet.append(status._json)
    status_df = pd.DataFrame(tweet,columns=['created_at','retweet_count','favorite_count','text'])
    status_df['name'] = df.name[i]
    status_df['party'] = df.party[i]
    tweet_df = tweet_df.append(status_df)
    print(str(i)+'/'+str(len(df)-1),df.name[i])
    time.sleep(75)

0/676 Danner Kline
1/676 Lee Auman
2/676 Mallory Hagan
3/676 Peter Joffrion
4/676 Robert Kennedy Jr.
5/676 Tabitha Isner
6/676 Terri Sewell
7/676 Gary Palmer
8/676 Mike Rogers
9/676 Alyse Galvin
10/676 Don Young
11/676 Anita Malik
12/676 Ann Kirkpatrick
13/676 David Brill
14/676 Hiral Tipirneni
15/676 Joan Greene
16/676 Raul Grijalva
17/676 Ruben Gallego
18/676 Tom O'Halleran
19/676 Andy Biggs
20/676 David Schweikert
21/676 Debbie Lesko
22/676 Lea Marquez Peterson
23/676 Steve Ferrara
24/676 Wendy Rogers
25/676 Chintan Desai
26/676 Clarke Tucker
27/676 Hayden Shamel
28/676 Joshua Mahony
29/676 Bruce Westerman
30/676 French Hill
31/676 Rick Crawford
32/676 Steve Womack
33/676 Alan Lowenthal
34/676 Ami Bera
35/676 Ammar Campa-Najjar
36/676 Andrew Janz
37/676 Anna Eshoo
38/676 Audrey Denney
39/676 Barbara Lee
40/676 Bryan Witt
41/676 Doris Matsui
42/676 Eric Swalwell
43/676 Gil Cisneros
44/676 Grace Napolitano
45/676 Harley Rouda
46/676 Jackie Speier
47/676 Jared Huffman
48/676 Jerry McNerney
49/676 Jessica Morse
50/676 Jimmy Gomez
51/676 Jimmy Panetta
52/676 John Garamendi
53/676 Josh Harder
54/676 Julia Brownley
55/676 Julia Peacock
56/676 Karen Bass
57/676 Katie Hill
58/676 Katie Porter
59/676 Lou Correa
60/676 Mark DeSaulnier
61/676 Mark Takano
62/676 Maxine Waters
63/676 Mike Levin
64/676 Mike Thompson
65/676 Nancy Pelosi
66/676 Nanette Barrag√°n
67/676 Norma Torres
68/676 Pete Aguilar
69/676 Raul Ruiz
70/676 Ro Khanna
71/676 Salud Carbajal
72/676 Scott Peters
73/676 TJ Cox
74/676 Tatiana Matta
75/676 Tony Cardenas
76/676 Zoe Lofgren
77/676 Aja Smith
78/676 Andrew Grant
79/676 Antonio Sabato Jr.
80/676 Christian Valiente
81/676 Dana Rohrabacher
82/676 Diane Harkey
83/676 Doug LaMalfa
84/676 Elizabeth Heng
85/676 Jeff Denham
86/676 John Fitzgerald
87/676 Johnny Nalbandian
88/676 Juan Hidalgo Jr.
89/676 Justin Fareed
90/676 Ken Calvert
91/676 Kenneth Wright
92/676 Kevin McCarthy
93/676 Kimberlin Brown Pelzer
94/676 Marla Livengood
95/676 Mimi Walters
96/676 Morgan Murtaugh
97/676 Omar Navarro
98/676 Ron Bassilian
99/676 Rudy Peters
100/676 Sean Flynn
101/676 Tim Donnelly
102/676 Tom McClintock
103/676 Young Kim
104/676 Diana DeGette
105/676 Diane Mitsch Bush
106/676 Ed Perlmutter
107/676 Jason Crow
108/676 Joe Neguse
109/676 Karen McCormick
110/676 Stephany Rose Spaulding
111/676 Casper Stockham
112/676 Ken Buck

KeyboardInterrupt:

In [13]:
for i in range(113,len(df)):
    tweet = []
    for status in tweepy.Cursor(api.user_timeline, screen_name='@'+df.twitter[i]).items():
        tweet.append(status._json)
    status_df = pd.DataFrame(tweet,columns=['created_at','retweet_count','favorite_count','text'])
    status_df['name'] = df.name[i]
    status_df['party'] = df.party[i]
    tweet_df = tweet_df.append(status_df)
    print(str(i)+'/'+str(len(df)-1),df.name[i])
    time.sleep(75)

113/676 Mike Coffman
114/676 Peter Yu
115/676 Scott Tipton
116/676 Jahana Hayes
117/676 Jim Himes
118/676 Joe Courtney
119/676 John Larson
120/676 Rosa DeLauro
121/676 Angel Cadena
122/676 Harry Arora
123/676 Manny Santos
124/676 Lisa Blunt Rochester
125/676 Alfred Lawson
126/676 Bob Rackleff
127/676 Charlie Crist
128/676 Chris Hunter
129/676 Darren Soto
130/676 David Holden
131/676 David Shapiro
132/676 Debbie Mucarsel-Powell
133/676 Debbie Wasserman Schultz
134/676 Donna Shalala
135/676 Ges Selmont
136/676 Jennifer Zimmerman
137/676 Kathy Castor
138/676 Kristen Carlson
139/676 Lauren Baer
140/676 Lois Frankel
141/676 Mary Barzee Flores
142/676 Nancy Soderberg
143/676 Sanjay Patel
144/676 Stephanie Murphy
145/676 Ted Deutch
146/676 Val Demings
147/676 Yvonne Hayes Hinson
148/676 Brian Mast
149/676 Carlos Curbelo
150/676 Daniel Webster
151/676 Francis Rooney
152/676 George Buck
153/676 Greg Steube
154/676 Joe Kaufman
155/676 John Rutherford
156/676 Maria Elvira Salazar
157/676 Mario Diaz-Balart
158/676 Matt Gaetz
159/676 Michael Waltz
160/676 Mike Miller
161/676 Neal Dunn
162/676 Nicolas Kimaz
163/676 Ross Spano
164/676 Virginia Fuller
165/676 Carolyn Bourdeaux
166/676 Chuck Enderlin
167/676 David Scott
168/676 Flynn Broady Jr.
169/676 Francys Johnson
170/676 Hank Johnson
171/676 Josh McCall
172/676 Lisa Ring
173/676 Barry Loudermilk
174/676 Doug Collins
175/676 Drew Ferguson
176/676 Earl "Buddy" Carter
177/676 Herman West Jr.
178/676 Jody Hice
179/676 Joe Profit
180/676 Karen Handel
181/676 Rick Allen
182/676 Tom Graves
183/676 Tulsi Gabbard
184/676 Brian Evans
185/676 Aaron Swisher
186/676 Michael Simpson
187/676 Russ Fulcher
188/676 Betsy Londrigan
189/676 Bill Foster
190/676 Brad Schneider
191/676 Brendan Kelly
192/676 Cheri Bustos
193/676 Jan Schakowsky
194/676 Junius Rodriguez
195/676 Kevin Gaither
196/676 Lauren Underwood
197/676 Mike Quigley
198/676 Raja Krishnamoorthi
199/676 Sara Dady
200/676 Sean Casten
201/676 Adam Kinzinger
202/676 Bill Fawell
203/676 Craig Cameron
204/676 Darin LaHood
205/676 Doug Bennett
206/676 Jitendra Diganvker
207/676 John Elleson
208/676 John Shimkus
209/676 Mark Wayne Lorch
210/676 Mike Bost
211/676 Nick Stella
212/676 Randy Hultgren
213/676 Rodney Davis
214/676 Andre Carson
215/676 Courtney Tritch
216/676 Dee Thornton
217/676 Jeannine Lee Lake
218/676 Liz Watson
219/676 Mel Hall
220/676 Peter Visclosky
221/676 Tobi Beck
222/676 William Tanoos
223/676 Greg Pence
224/676 Jackie Walorski

TweepError: Twitter error response: status code = 500

In [14]:
for i in range(225,len(df)):
    tweet = []
    for status in tweepy.Cursor(api.user_timeline, screen_name='@'+df.twitter[i]).items():
        tweet.append(status._json)
    status_df = pd.DataFrame(tweet,columns=['created_at','retweet_count','favorite_count','text'])
    status_df['name'] = df.name[i]
    status_df['party'] = df.party[i]
    tweet_df = tweet_df.append(status_df)
    print(str(i)+'/'+str(len(df)-1),df.name[i])
    time.sleep(75)

225/676 James Baird
226/676 Jim Banks
227/676 Larry Bucshon
228/676 Susan Brooks
229/676 Trey Hollingsworth
230/676 Wayne Harmon
231/676 Abby Finkenauer
232/676 Cindy Axne
233/676 Dave Loebsack
234/676 J.D. Scholten
235/676 Chris Peters
236/676 David Young
237/676 Rod Blum
238/676 Steve King
239/676 Alan LaPolice
240/676 James Thompson
241/676 Paul Davis
242/676 Sharice Davids
243/676 Kevin Yoder
244/676 Roger Marshall
245/676 Ron Estes
246/676 Steve Watkins

TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?screen_name=%40amymcgrathky (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1191824e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

In [15]:
for i in range(247,len(df)):
    tweet = []
    for status in tweepy.Cursor(api.user_timeline, screen_name='@'+df.twitter[i]).items():
        tweet.append(status._json)
    status_df = pd.DataFrame(tweet,columns=['created_at','retweet_count','favorite_count','text'])
    status_df['name'] = df.name[i]
    status_df['party'] = df.party[i]
    tweet_df = tweet_df.append(status_df)
    print(str(i)+'/'+str(len(df)-1),df.name[i])
    time.sleep(75)

247/676 Amy McGrath
248/676 Hank Linderman
249/676 Paul Walker
250/676 Seth Hall
251/676 Andy Barr
252/676 Brett Guthrie
253/676 James Comer Jr.
254/676 Thomas Massie
255/676 Vickie Yates Glisson
256/676 Andie Saizan
257/676 Cedric Richmond
258/676 Jim Francis
259/676 Justin DeWitt
260/676 Mildred Methvin
261/676 Rob Anderson
262/676 Ryan Trundle
263/676 Tammy Savoie
264/676 Clay Higgins
265/676 Garret Graves
266/676 Josh Guillory
267/676 Mike Johnson
268/676 Ralph Abraham
269/676 Steve Scalise

KeyboardInterrupt:

In [17]:
for i in range(270,len(df)):
    tweet = []
    for status in tweepy.Cursor(api.user_timeline, screen_name='@'+df.twitter[i]).items():
        tweet.append(status._json)
    status_df = pd.DataFrame(tweet,columns=['created_at','retweet_count','favorite_count','text'])
    status_df['name'] = df.name[i]
    status_df['party'] = df.party[i]
    tweet_df = tweet_df.append(status_df)
    print(str(i)+'/'+str(len(df)-1),df.name[i])
    time.sleep(75)

270/676 Jared Golden
271/676 Bruce Poliquin
272/676 Mark Holbrook
273/676 Anthony Brown
274/676 David Trone
275/676 Elijah Cummings
276/676 Jamie Raskin
277/676 Jesse Colvin
278/676 John Sarbanes
279/676 Steny Hoyer
280/676 Amie Hoeber
281/676 Andrew Harris
282/676 George McDermott
283/676 Liz Matory
284/676 Richmond Davis
285/676 William Devine III
286/676 Ayanna Pressley
287/676 Bill Keating
288/676 Jim McGovern
289/676 Joseph Kennedy III
290/676 Katherine Clark
291/676 Lori Trahan
292/676 Seth Moulton
293/676 John Hugo
294/676 Rick Green
295/676 Tracy Lovvorn
296/676 Andy Levin
297/676 Brenda Lawrence
298/676 Cathy Albro
299/676 Dan Kildee
300/676 Debbie Dingell
301/676 Elissa Slotkin
302/676 Gretchen Driskell
303/676 Haley Stevens
304/676 Matt Longjohn
305/676 Rashida Tlaib
306/676 Rob Davidson
307/676 Candius Stearns
308/676 Fred Upton
309/676 Jack Bergman
310/676 Jeff Jones
311/676 John Moolenaar
312/676 Justin Amash
313/676 Lena Epstein
314/676 Michael Bishop
315/676 Paul Mitchell
316/676 Tim Walberg
317/676 Travis Wines
318/676 Angie Craig
319/676 Betty McCollum
320/676 Collin Peterson
321/676 Dan Feehan
322/676 Dean Phillips
323/676 Ian Todd
324/676 Ilhan Omar
325/676 Joe Radinovich
326/676 Dave Hughes
327/676 Erik Paulsen
328/676 Greg Ryan
329/676 Jason Lewis
330/676 Jennifer Zielinski
331/676 Jim Hagedorn
332/676 Pete Stauber
333/676 Tom Emmer
334/676 Jeramey Anderson
335/676 Michael Evans
336/676 Randy Wadkins
337/676 Michael Guest
338/676 Steven Palazzo
339/676 Trent Kelly
340/676 Cort VanOstran
341/676 Emanuel Cleaver
342/676 Henry Martin

KeyboardInterrupt:

In [18]:
for i in range(343,len(df)):
    tweet = []
    for status in tweepy.Cursor(api.user_timeline, screen_name='@'+df.twitter[i]).items():
        tweet.append(status._json)
    status_df = pd.DataFrame(tweet,columns=['created_at','retweet_count','favorite_count','text'])
    status_df['name'] = df.name[i]
    status_df['party'] = df.party[i]
    tweet_df = tweet_df.append(status_df)
    print(str(i)+'/'+str(len(df)-1),df.name[i])
    time.sleep(75)

343/676 Jamie Schoolcraft
344/676 Kathy Ellis
345/676 Katy Geppert
346/676 Renee Hoagenson
347/676 Ann Wagner
348/676 Billy Long
349/676 Blaine Luetkemeyer
350/676 Jason Smith
351/676 Vicky Hartzler
352/676 Kathleen Williams
353/676 Greg Gianforte
354/676 Kara Eastman
355/676 Paul Theobald
356/676 Clint Koble
357/676 Susie Lee
358/676 Cresent Hardy
359/676 Danny Tarkanian
360/676 Joyce Bentley
361/676 Mark Amodei
362/676 Annie Kuster
363/676 Chris Pappas
364/676 Eddie Edwards
365/676 Steve Negron
366/676 Andrew Kim

KeyboardInterrupt:

In [19]:
for i in range(367,len(df)):
    tweet = []
    for status in tweepy.Cursor(api.user_timeline, screen_name='@'+df.twitter[i]).items():
        tweet.append(status._json)
    status_df = pd.DataFrame(tweet,columns=['created_at','retweet_count','favorite_count','text'])
    status_df['name'] = df.name[i]
    status_df['party'] = df.party[i]
    tweet_df = tweet_df.append(status_df)
    print(str(i)+'/'+str(len(df)-1),df.name[i])
    time.sleep(75)

367/676 Bill Pascrell
368/676 Donald Norcross
369/676 Frank Pallone
370/676 Josh Gottheimer
371/676 Josh Welle
372/676 Mikie Sherrill
373/676 Tom Malinowski
374/676 Daryl Kipnis
375/676 Jay Webber
376/676 John McCann
377/676 Leonard Lance
378/676 Seth Grossman
379/676 Tom MacArthur
380/676 Ben Ray Lujan
381/676 Debra Haaland
382/676 Xochitl Torres Small
383/676 Janice Arnold-Jones
384/676 Yvette Herrell
385/676 Adriano Espaillat
386/676 Alexandria Ocasio-Cortez
387/676 Anthony Brindisi
388/676 Antonio Delgado
389/676 Brian Higgins
390/676 Carolyn Maloney
391/676 Dana Balter
392/676 Grace Meng
393/676 Hakeem Jeffries
394/676 Jose Serrano
395/676 Joseph Crowley
396/676 Joseph Morelle
397/676 Kathleen Rice
398/676 Liuba Grechen Shirley
399/676 Max Rose
400/676 Nate McMurray
401/676 Nydia Velazquez
402/676 Paul Tonko
403/676 Perry Gershon
404/676 Tedra Cobb
405/676 Tom Suozzi
406/676 Tracy Mitrano
407/676 Yvette Clarke
408/676 Ameer Benno
409/676 Chris Collins
410/676 Claudia Tenney
411/676 Dan DeBono
412/676 Daniel Donovan
413/676 Elise Stefanik
414/676 James O'Donnell
415/676 Jineea Butler
416/676 Joe Vitollo
417/676 John Faso
418/676 Lee Zeldin
419/676 Lutchi Gayot
420/676 Naomi Levin
421/676 Peter King
422/676 Tom Reed
423/676 Alma Adams
424/676 Dan McCready
425/676 David Price
426/676 David Wilson Brown
427/676 Denise Adams
428/676 Frank McNeill
429/676 Kathy Manning
430/676 Kyle Horton
431/676 Linda Coleman
432/676 Phillip Price
433/676 Ryan Watts
434/676 David Rouzer
435/676 Mark Harris
436/676 Mark Walker
437/676 Patrick McHenry
438/676 Richard Hudson
439/676 Roger Allison
440/676 Steve Von Loor
441/676 Ted Budd
442/676 Virginia Foxx
443/676 Walter Jones
444/676 Mac Schneider
445/676 Kelly Armstrong
446/676 Aftab Pureval
447/676 Betsy Rader
448/676 Danny O'Connor
449/676 Janet Garrett
450/676 Jill Schiller
451/676 John Michael Galbraith
452/676 Joyce Beatty
453/676 Ken Harbaugh
454/676 Marcia Fudge
455/676 Marcy Kaptur
456/676 Rick Neal
457/676 Shawna Roberts
458/676 Susan Moran Palmer
459/676 Theresa Gasper
460/676 Tim Ryan
461/676 Vanessa Enoch
462/676 Anthony Gonzalez
463/676 Beverly Goldstein
464/676 Bill Johnson
465/676 Bob Gibbs
466/676 Bob Latta
467/676 Brad Wenstrup
468/676 Jim Burgess
469/676 Jim Jordan
470/676 Michael Turner
471/676 Steve Chabot
472/676 Steve Stivers
473/676 Steven Kraus
474/676 Troy Balderson
475/676 Warren Davidson
476/676 Jason Nichols
477/676 Kendra Horn
478/676 Mary Brannon
479/676 Tim Gilpin
480/676 Frank Lucas
481/676 Kevin Hern
482/676 Markwayne Mullin
483/676 Steve Russell
484/676 Earl Blumenauer
485/676 Jamie McLeod-Skinner
486/676 Kurt Schrader
487/676 Peter DeFazio
488/676 Art Robinson
489/676 Greg Walden
490/676 Mark Callahan
491/676 Bibiana Boerio
492/676 Brent Ottaway
493/676 Chrissy Houlahan
494/676 Conor Lamb
495/676 Denny Wolff
496/676 Dwight Evans
497/676 George Scott
498/676 Jessica King
499/676 Madeleine Dean
500/676 Marc Friedenberg
501/676 Mary Gay Scanlon
502/676 Ronald DiNicola
503/676 Scott Wallace
504/676 Susan Wild
505/676 Brian Fitzpatrick
506/676 Glenn Thompson
507/676 Greg McCauley
508/676 Guy Reschenthaler
509/676 John Chrin
510/676 Mike Kelly
511/676 Pearl Kim
512/676 Scott Perry
513/676 David Cicilline
514/676 Jim Langevin
515/676 Salvatore Caiozzo
516/676 Archie Parnell
517/676 Joe Cunningham
518/676 Sean Carrigan
519/676 Jeff Duncan
520/676 Joe Wilson
521/676 Katie Arrington
522/676 Tom Rice
523/676 William Timmons
524/676 Timothy Bjorkman
525/676 Dusty Johnson
526/676 Danielle Mitchell
527/676 Dawn Barlow
528/676 Jim Cooper
529/676 Justin Kanew
530/676 Mariah Phillips
531/676 Renee Hoyos
532/676 Steve Cohen
533/676 Charles Fleischmann
534/676 Charlotte Bergmann
535/676 David Kustoff
536/676 Jody Ball
537/676 Mark Green
538/676 Scott DesJarlais
539/676 Tim Burchett
540/676 Adrienne Bell
541/676 Al Green
542/676 Catherine Krantz
543/676 Colin Allred
544/676 Dan Wood
545/676 Dayna Steele
546/676 Eric Holguin
547/676 Gina Ortiz Jones
548/676 Jan McDowell
549/676 Jana Lynne Sanchez
550/676 Jennie Lou Leeder
551/676 Joaquin Castro
552/676 Joseph Kopser
553/676 Julie Oliver
554/676 Linsey Fagan
555/676 Lizzie Pannill Fletcher
556/676 Lloyd Doggett
557/676 Lorie Burch
558/676 M.J. Hegar
559/676 Marc Veasey
560/676 Miguel Levario
561/676 Rick Kennedy
562/676 Shirley McKellar
563/676 Steven David
564/676 Sylvia Garcia
565/676 Todd Litton
566/676 Vanessa Adia
567/676 Veronica Escobar
568/676 Ava Pate
569/676 Bill Flores
570/676 Brian Babin
571/676 Chip Roy
572/676 Daniel Crenshaw
573/676 Jodey Arrington
574/676 John Carter
575/676 John Culberson
576/676 John Ratcliffe
577/676 Kenny Marchant
578/676 Kevin Brady
579/676 Mac Thornberry
580/676 Michael McCaul
581/676 Pete Olson
582/676 Pete Sessions
583/676 Phillip Aronoff
584/676 Randy Weber
585/676 Roger Williams
586/676 Ronald Wright
587/676 Van Taylor
588/676 Will Hurd
589/676 Ben McAdams
590/676 James Singer

KeyboardInterrupt:

In [20]:
for i in range(591,len(df)):
    tweet = []
    for status in tweepy.Cursor(api.user_timeline, screen_name='@'+df.twitter[i]).items():
        tweet.append(status._json)
    status_df = pd.DataFrame(tweet,columns=['created_at','retweet_count','favorite_count','text'])
    status_df['name'] = df.name[i]
    status_df['party'] = df.party[i]
    tweet_df = tweet_df.append(status_df)
    print(str(i)+'/'+str(len(df)-1),df.name[i])
    time.sleep(75)

591/676 Lee Castillo
592/676 Shireen Ghorbani
593/676 Chris Stewart
594/676 John Curtis
595/676 Mia Love
596/676 Rob Bishop
597/676 Peter Welch
598/676 Abigail Spanberger
599/676 Anthony Flaccavento
600/676 Bobby Scott
601/676 Donald McEachin
602/676 Elaine Luria
603/676 Gerald Connolly
604/676 Jennifer Lewis
605/676 Jennifer Wexton
606/676 Vangie Williams
607/676 Barbara Comstock
608/676 Ben Cline
609/676 Jeff Dove
610/676 Morgan Griffith
611/676 Rob Wittman
612/676 Ryan McAdams
613/676 Scott Taylor
614/676 Thomas Oh
615/676 Adam Smith
616/676 Carolyn Long
617/676 Christine Brown
618/676 Derek Kilmer
619/676 Kim Schrier
620/676 Lisa Brown
621/676 Pramila Jayapal
622/676 Rick Larsen
623/676 Sarah Smith
624/676 Suzan DelBene
625/676 Cathy McMorris Rodgers
626/676 Dino Rossi
627/676 Jaime Herrera Beutler
628/676 Kendra Fershee
629/676 Richard Ojeda
630/676 Talley Sergent
631/676 Alexander Mooney
632/676 Carol Miller
633/676 Beau Liegeois
634/676 Dan Kohl
635/676 Gwen Moore
636/676 Margaret Engebretson
637/676 Mark Pocan
638/676 Randy Bryce
639/676 Ron Kind
640/676 Tom Palzewicz
641/676 Bryan Steil
642/676 Glenn Grothman
643/676 Michael Gallagher
644/676 Sean Duffy
645/676 Steve Toft
646/676 Bradley Byrne
647/676 Nicolas Pierson
648/676 Jennifer Nye
649/676 Cam Cavasso
650/676 Jessee Carlton Fleenor
651/676 Joseph Schneider
652/676 Peter Tedeschi
653/676 Jerry Hilliard
654/676 Jessica McClure
655/676 Paul Dilks
656/676 James Maxwell
657/676 Renee Zeno
658/676 Christopher DePizzo
659/676 Dan David
660/676 Mary Geren
661/676 David Smalling
662/676 Wayne Liebnitzky
663/676 Kimberly Bizon
664/676 Matt Cartwright
665/676 Susan Boser
666/676 Bryan Leib
667/676 Dan Meuser
668/676 John Joyce
669/676 Marty Nothstein
670/676 Brandon Brown
671/676 Marty Olsen
672/676 Vicente Gonz√°lez
673/676 Leslie Cockburn
674/676 David Brat
675/676 Denver Riggleman
676/676 Matt Cartwright

In [21]:
tweet_df.head()

,created_at,retweet_count,favorite_count,text,name,party
0,Wed Oct 17 00:08:49 +0000 2018,46,67,Only 3 wks left. Have you reached out to every...,Danner Kline,Democratic
1,Sun Oct 14 22:34:11 +0000 2018,6,0,RT @lisawborden: Done with another afternoon o...,Danner Kline,Democratic
2,Thu Oct 11 03:27:43 +0000 2018,10,0,RT @HIVEAlabama: Went to this fundraiser for @...,Danner Kline,Democratic
3,Thu Oct 11 03:27:30 +0000 2018,2,9,@HIVEAlabama @drivebytruckers Pointing helps p...,Danner Kline,Democratic
4,Mon Oct 08 20:45:02 +0000 2018,34,44,I'm running for Congress to fight for working ...,Danner Kline,Democratic

In [22]:
tweet_df.tail()

,created_at,retweet_count,favorite_count,text,name,party
1954,Fri Jan 11 20:10:50 +0000 2013,0,1,"Hey Folks, I have a couple minutes. Anyone hav...",Matt Cartwright,Democratic
1955,Fri Jan 11 15:41:59 +0000 2013,1,0,RT @TLAndrewSeder: #FF to some of my recent fo...,Matt Cartwright,Democratic
1956,Tue Jan 08 15:49:50 +0000 2013,0,0,On my way back from the Congressional Research...,Matt Cartwright,Democratic
1957,Mon Jan 07 23:18:55 +0000 2013,0,0,"Pennsylvania, 17th House District - http://t.c...",Matt Cartwright,Democratic
1958,Mon Jan 07 23:12:35 +0000 2013,0,0,Honored to have been selected as Democratic Fr...,Matt Cartwright,Democratic

In [23]:
len(tweet_df)

820360

In [24]:
tweet_df.to_csv('tweepy_raw.csv',index=False)

In [25]:
tweet_df.created_at = pd.to_datetime(tweet_df.created_at,format='%a %b %d %H:%M:%S +0000 %Y')

In [26]:
tweet_df = tweet_df[tweet_df.created_at.between('2018-01-01','2018-10-10')].reset_index(drop=True)

In [27]:
len(tweet_df)

337786

In [28]:
tweet_df.retweet_count = tweet_df.retweet_count.astype(int)
tweet_df.favorite_count = tweet_df.favorite_count.astype(int)

In [30]:
tweet_df = tweet_df[~tweet_df.text.str.contains(r'\b(RT)')].reset_index(drop=True)

/Users/kazuhiro.kida/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """Entry point for launching an IPython kernel.

In [31]:
len(tweet_df)

240001

In [32]:
tweet_df.head()

,created_at,retweet_count,favorite_count,text,name,party
0,2018-10-08 20:45:02,34,44,I'm running for Congress to fight for working ...,Danner Kline,Democratic
1,2018-10-05 13:59:30,18,29,My case for what is at stake in the Kavanaugh ...,Danner Kline,Democratic
2,2018-10-04 19:19:09,28,74,"""Due process"" applies to crim. prosecutions, n...",Danner Kline,Democratic
3,2018-10-03 03:41:31,50,152,I wonder how many times we will need to cover ...,Danner Kline,Democratic
4,2018-09-28 14:22:06,45,172,So proud my senator is standing on the right s...,Danner Kline,Democratic

In [33]:
tweet_df.to_csv('tweepy.csv',index=False)

## Tweets by candidate

In [34]:
tweet_df.groupby(by='name').mean()

                          retweet_count  favorite_count
name
Aaron Swisher                  3.163265        5.566327
Abby Finkenauer               23.771795       77.407692
Abigail Spanberger            29.395604       75.644970
Adam Kinzinger                10.333333       27.444444
Adam Smith                     1.524590        6.202186
Adriano Espaillat              9.250000       42.250000
Adrienne Bell                 17.788210       37.973071
Aftab Pureval                 49.841791      183.662687
Aja Smith                     48.151052       65.290631
Alan LaPolice                  3.771930        7.070175
Alan Lowenthal                 0.706311        1.946602
Alexander Mooney               2.293333        6.306667
Alexandria Ocasio-Cortez     716.173162     3512.950841
Alfred Lawson                  0.482270        1.262411
Alma Adams                     3.000000        9.333333
Alyse Galvin                   6.543367       19.433673
Ameer Benno                    0.669951        1.546798
Ami Bera                       3.928302        7.856604
Amie Hoeber                    0.519481        2.415584
Ammar Campa-Najjar            71.593701      210.174803
Amy McGrath                  148.872464      562.472464
Andie Saizan                   1.743119        3.582569
Andre Carson                   2.446809        6.595745
Andrew Grant                   1.492308        3.917949
Andrew Janz                  772.585749     1755.149758
Andrew Kim                    36.598291       95.251282
Andy Barr                     11.054348       28.398551
Andy Biggs                     9.950000       22.883333
Andy Levin                     2.923944        8.033803
Angel Cadena                   0.289855        0.637681
...                                 ...             ...
Tracy Lovvorn                  2.782609        5.539130
Tracy Mitrano                 10.270019       21.666667
Travis Wines                   1.548476        6.102493
Trey Hollingsworth             2.937500       11.687500
Troy Balderson                36.061856       86.498282
Tulsi Gabbard                251.166428      608.035868
Val Demings                    0.800000        2.800000
Van Taylor                     3.265101       12.177852
Vanessa Adia                  11.714047       29.866221
Vanessa Enoch                  7.108374       12.913793
Vangie Williams               10.040138       22.950688
Veronica Escobar              12.532238       41.331226
Vickie Yates Glisson           2.855172       10.717241
Vicky Hartzler                 1.144000        3.856000
Virginia Foxx                  1.884615        3.500000
Virginia Fuller                0.764706        1.329412
Walter Jones                   0.275862        1.155172
Warren Davidson                0.000000        1.000000
Wayne Liebnitzky               4.782609        6.521739
Wendy Rogers                   7.324138       11.332759
Will Hurd                      2.423077        9.288462
William Devine III             0.000000        0.133333
William Tanoos                 6.132075       14.537736
William Timmons                3.000000       11.619048
Xochitl Torres Small          14.654709       42.565022
Young Kim                      9.512346       20.111111
Yvette Clarke                  2.197044        7.266010
Yvette Herrell                12.047619       21.752381
Yvonne Hayes Hinson            1.594828        4.732759
Zoe Lofgren                    0.470588        1.411765

[650 rows x 2 columns]

In [35]:
count_df = tweet_df.groupby(by='name').mean().reset_index()

In [36]:
count_df.columns = ['name','ave_retweet','ave_favorite']

In [37]:
count_df.head()

                 name  ave_retweet  ave_favorite
0       Aaron Swisher     3.163265      5.566327
1     Abby Finkenauer    23.771795     77.407692
2  Abigail Spanberger    29.395604     75.644970
3      Adam Kinzinger    10.333333     27.444444
4          Adam Smith     1.524590      6.202186

In [38]:
tweet_df.groupby(by='name').sum()

                          retweet_count  favorite_count
name
Aaron Swisher                       620            1091
Abby Finkenauer                    9271           30189
Abigail Spanberger                34775           89488
Adam Kinzinger                      279             741
Adam Smith                          279            1135
Adriano Espaillat                    74             338
Adrienne Bell                     24441           52175
Aftab Pureval                     16697           61527
Aja Smith                         50366           68294
Alan LaPolice                       215             403
Alan Lowenthal                      291             802
Alexander Mooney                    172             473
Alexandria Ocasio-Cortez        1617119         7932243
Alfred Lawson                        68             178
Alma Adams                           27              84
Alyse Galvin                       2565            7618
Ameer Benno                         136             314
Ami Bera                           1041            2082
Amie Hoeber                          40             186
Ammar Campa-Najjar                45462          133461
Amy McGrath                      154083          582159
Andie Saizan                        380             781
Andre Carson                        115             310
Andrew Grant                        582            1528
Andrew Janz                     1279402         2906528
Andrew Kim                        21410           55722
Andy Barr                          3051            7838
Andy Biggs                          597            1373
Andy Levin                         1038            2852
Angel Cadena                         20              44
...                                 ...             ...
Tracy Lovvorn                       320             637
Tracy Mitrano                      5515           11635
Travis Wines                        559            2203
Trey Hollingsworth                   47             187
Troy Balderson                    10494           25171
Tulsi Gabbard                    175063          423801
Val Demings                           4              14
Van Taylor                          973            3629
Vanessa Adia                       7005           17860
Vanessa Enoch                      5772           10486
Vangie Williams                    8755           20013
Veronica Escobar                   9913           32693
Vickie Yates Glisson                414            1554
Vicky Hartzler                      143             482
Virginia Foxx                        49              91
Virginia Fuller                      65             113
Walter Jones                         16              67
Warren Davidson                       0               1
Wayne Liebnitzky                    220             300
Wendy Rogers                       4248            6573
Will Hurd                           126             483
William Devine III                    0               4
William Tanoos                     1300            3082
William Timmons                     126             488
Xochitl Torres Small               3268            9492
Young Kim                          1541            3258
Yvette Clarke                       446            1475
Yvette Herrell                     1265            2284
Yvonne Hayes Hinson                 185             549
Zoe Lofgren                           8              24

[650 rows x 2 columns]

In [39]:
count_df = pd.merge(count_df,tweet_df.groupby(by='name').sum().reset_index(),on='name')

In [40]:
count_df.head()

,name,ave_retweet,ave_favorite,retweet_count,favorite_count
0,Aaron Swisher,3.163265,5.566327,620,1091
1,Abby Finkenauer,23.771795,77.407692,9271,30189
2,Abigail Spanberger,29.395604,75.644970,34775,89488
3,Adam Kinzinger,10.333333,27.444444,279,741
4,Adam Smith,1.524590,6.202186,279,1135

In [41]:
tweet_df.groupby(by='name').text.count().reset_index()

                         name  text
0               Aaron Swisher   196
1             Abby Finkenauer   390
2          Abigail Spanberger  1183
3              Adam Kinzinger    27
4                  Adam Smith   183
5           Adriano Espaillat     8
6               Adrienne Bell  1374
7               Aftab Pureval   335
8                   Aja Smith  1046
9               Alan LaPolice    57
10             Alan Lowenthal   412
11           Alexander Mooney    75
12   Alexandria Ocasio-Cortez  2258
13              Alfred Lawson   141
14                 Alma Adams     9
15               Alyse Galvin   392
16                Ameer Benno   203
17                   Ami Bera   265
18                Amie Hoeber    77
19         Ammar Campa-Najjar   635
20                Amy McGrath  1035
21               Andie Saizan   218
22               Andre Carson    47
23               Andrew Grant   390
24                Andrew Janz  1656
25                 Andrew Kim   585
26                  Andy Barr   276
27                 Andy Biggs    60
28                 Andy Levin   355
29               Angel Cadena    69
..                        ...   ...
620             Tracy Lovvorn   115
621             Tracy Mitrano   537
622              Travis Wines   361
623        Trey Hollingsworth    16
624            Troy Balderson   291
625             Tulsi Gabbard   697
626               Val Demings     5
627                Van Taylor   298
628              Vanessa Adia   598
629             Vanessa Enoch   812
630           Vangie Williams   872
631          Veronica Escobar   791
632      Vickie Yates Glisson   145
633            Vicky Hartzler   125
634             Virginia Foxx    26
635           Virginia Fuller    85
636              Walter Jones    58
637           Warren Davidson     1
638          Wayne Liebnitzky    46
639              Wendy Rogers   580
640                 Will Hurd    52
641        William Devine III    30
642            William Tanoos   212
643           William Timmons    42
644      Xochitl Torres Small   223
645                 Young Kim   162
646             Yvette Clarke   203
647            Yvette Herrell   105
648       Yvonne Hayes Hinson   116
649               Zoe Lofgren    17

[650 rows x 2 columns]

In [42]:
count_df = pd.merge(count_df,tweet_df.groupby(by='name').text.count().reset_index(),on='name')

In [43]:
count_df = count_df.rename({'text':'tweet_count'},axis=1)

In [44]:
count_df.head()

,name,ave_retweet,ave_favorite,retweet_count,favorite_count,tweet_count
0,Aaron Swisher,3.163265,5.566327,620,1091,196
1,Abby Finkenauer,23.771795,77.407692,9271,30189,390
2,Abigail Spanberger,29.395604,75.644970,34775,89488,1183
3,Adam Kinzinger,10.333333,27.444444,279,741,27
4,Adam Smith,1.524590,6.202186,279,1135,183

In [45]:
len(count_df)

650

## Merge with original dataframe

In [46]:
df.head()

,district,name,party,state,twitter,url,district_N
0,"Candidate, U.S. House Alabama District 6",Danner Kline,Democratic,Alabama,votedannerkline,https://ballotpedia.org/Danner_Kline,6
1,"Candidate, U.S. House Alabama District 4",Lee Auman,Democratic,Alabama,LeeAuman2018,https://ballotpedia.org/Lee_Auman,4
2,"Candidate, U.S. House Alabama District 3",Mallory Hagan,Democratic,Alabama,HaganforHouse,https://ballotpedia.org/Mallory_Hagan,3
3,"Candidate, U.S. House Alabama District 5",Peter Joffrion,Democratic,Alabama,peter_joffrion,https://ballotpedia.org/Peter_Joffrion,5
4,"Candidate, U.S. House Alabama District 1",Robert Kennedy Jr.,Democratic,Alabama,Kennedy4Alabama,https://ballotpedia.org/Robert_Kennedy_Jr._(Al...,1

In [47]:
df.dtypes

district      object
name          object
party         object
state         object
twitter       object
url           object
district_N     int64
dtype: object

In [48]:
df.district_N = df.district_N.astype(str)

In [49]:
for i in range(0,len(df)):
    if len(df.iloc[i,6]) == 1:
        df.iloc[i,6] = '0' + df.iloc[i,6]

In [50]:
df.head()

,district,name,party,state,twitter,url,district_N
0,"Candidate, U.S. House Alabama District 6",Danner Kline,Democratic,Alabama,votedannerkline,https://ballotpedia.org/Danner_Kline,06
1,"Candidate, U.S. House Alabama District 4",Lee Auman,Democratic,Alabama,LeeAuman2018,https://ballotpedia.org/Lee_Auman,04
2,"Candidate, U.S. House Alabama District 3",Mallory Hagan,Democratic,Alabama,HaganforHouse,https://ballotpedia.org/Mallory_Hagan,03
3,"Candidate, U.S. House Alabama District 5",Peter Joffrion,Democratic,Alabama,peter_joffrion,https://ballotpedia.org/Peter_Joffrion,05
4,"Candidate, U.S. House Alabama District 1",Robert Kennedy Jr.,Democratic,Alabama,Kennedy4Alabama,https://ballotpedia.org/Robert_Kennedy_Jr._(Al...,01

In [51]:
count_df['state'] = np.nan
count_df['district_N'] = np.nan
count_df['party'] = np.nan

In [52]:
count_df.head()

,name,ave_retweet,ave_favorite,retweet_count,favorite_count,tweet_count,state,district_N,party
0,Aaron Swisher,3.163265,5.566327,620,1091,196,NaN,NaN,NaN
1,Abby Finkenauer,23.771795,77.407692,9271,30189,390,NaN,NaN,NaN
2,Abigail Spanberger,29.395604,75.644970,34775,89488,1183,NaN,NaN,NaN
3,Adam Kinzinger,10.333333,27.444444,279,741,27,NaN,NaN,NaN
4,Adam Smith,1.524590,6.202186,279,1135,183,NaN,NaN,NaN

In [53]:
for i in range(0,len(count_df)):
    for j in range(0,len(df)):
        if count_df.iloc[i,0] == df.iloc[j,1]:
            count_df.iloc[i,6] = df.iloc[j,3]
            count_df.iloc[i,7] = df.iloc[j,6]
            count_df.iloc[i,8] = df.iloc[j,2]

In [54]:
count_df.head()

,name,ave_retweet,ave_favorite,retweet_count,favorite_count,tweet_count,state,district_N,party
0,Aaron Swisher,3.163265,5.566327,620,1091,196,Idaho,02,Democratic
1,Abby Finkenauer,23.771795,77.407692,9271,30189,390,Iowa,01,Democratic
2,Abigail Spanberger,29.395604,75.644970,34775,89488,1183,Virginia,07,Democratic
3,Adam Kinzinger,10.333333,27.444444,279,741,27,Illinois,16,Republican
4,Adam Smith,1.524590,6.202186,279,1135,183,Washington,09,Democratic

In [55]:
count_df.to_csv('tweet_average_count.csv',index=False)

## Followers count

In [56]:
twitter_count = []
for candidate in df.twitter:
    try:
        user = api.get_user('@'+candidate)
        user_dic ={}
        user_dic['name'] = user.name
        user_dic['followers'] = user.followers_count
    except:
        pass
    twitter_count.append(user_dic)

In [57]:
followers_df = pd.DataFrame(twitter_count)

In [58]:
followers_df.head()

   followers                         name
0       4291                 Danner Kline
1       1922                    Lee Auman
2       5036                Mallory Hagan
3       5528  Peter Joffrion for Congress
4       2888          Robert Kennedy, Jr.

In [59]:
followers_df = followers_df.sort_values(by='followers',ascending=False)

In [60]:
followers_df.to_csv('followers_count',index=False)

In [61]:
len(followers_df)

677

## Text analysis

In [62]:
from collections import Counter

In [63]:
tweet_df.head()

,created_at,retweet_count,favorite_count,text,name,party
0,2018-10-08 20:45:02,34,44,I'm running for Congress to fight for working ...,Danner Kline,Democratic
1,2018-10-05 13:59:30,18,29,My case for what is at stake in the Kavanaugh ...,Danner Kline,Democratic
2,2018-10-04 19:19:09,28,74,"""Due process"" applies to crim. prosecutions, n...",Danner Kline,Democratic
3,2018-10-03 03:41:31,50,152,I wonder how many times we will need to cover ...,Danner Kline,Democratic
4,2018-09-28 14:22:06,45,172,So proud my senator is standing on the right s...,Danner Kline,Democratic

In [64]:
Counter(" ".join(tweet_df.text).lower().split()).most_common()

[('the', 150035),
 ('to', 134224),
 ('and', 76218),
 ('a', 67296),
 ('in', 65462),
 ('of', 65442),
 ('for', 62265),
 ('is', 46627),
 ('i', 42584),
 ('you', 38508),
 ('we', 37782),
 ('our', 36553),
 ('this', 33550),
 ('on', 29141),
 ('with', 26755),
 ('are', 24165),
 ('that', 23473),
 ('at', 23176),
 ('my', 20684),
 ('have', 20273),
 ('thank', 19697),
 ('be', 18574),
 ('your', 17085),
 ('it', 15509),
 ('from', 14205),
 ('will', 13575),
 ('great', 13305),
 ('who', 13229),
 ('all', 12877),
 ('was', 12307),
 ('as', 12097),
 ('so', 11797),
 ('by', 11635),
 ('not', 11616),
 ('&amp;', 11610),
 ('about', 11511),
 ('out', 10497),
 ('has', 9926),
 ('an', 9750),
 ('up', 8648),
 ('us', 8429),
 ('more', 8406),
 ('their', 8293),
 ('people', 8282),
 ('if', 8269),
 ('can', 8232),
 ('-', 8226),
 ('but', 8183),
 ('time', 7984),
 ('need', 7693),
 ('me', 7621),
 ('what', 7538),
 ('they', 7374),
 ('thanks', 7286),
 ('today', 6982),
 ('one', 6920),
 ('just', 6854),
 ('day', 6751),
 ('his', 6715),
 ('support', 6683),
 ('get', 6647),
 ('he', 6442),
 ('do', 6287),
 ('when', 6282),
 ('new', 6157),
 ('campaign', 6087),
 ('make', 5993),
 ('am', 5860),
 ('join', 5826),
 ('had', 5711),
 ('like', 5603),
 ('congress', 5545),
 ('been', 5497),
 ('proud', 5471),
 ('last', 5447),
 ('i‚Äôm', 5266),
 ('it‚Äôs', 5212),
 ('no', 5161),
 ('how', 5121),
 ('see', 5101),
 ('help', 5040),
 ('vote', 4995),
 ("i'm", 4837),
 ('work', 4776),
 ('trump', 4759),
 ("it's", 4712),
 ('or', 4679),
 ('many', 4389),
 ('should', 4350),
 ('county', 4339),
 ('every', 4282),
 ('know', 4266),
 ('working', 4241),
 ('would', 4072),
 ('over', 4057),
 ('there', 4036),
 ('good', 4018),
 ('than', 4008),
 ('want', 4003),
 ('take', 3914),
 ('these', 3873),
 ('here', 3862),
 ('only', 3839),
 ('why', 3812),
 ('women', 3789),
 ('must', 3778),
 ('first', 3759),
 ('now', 3758),
 ('happy', 3618),
 ('some', 3606),
 ('t‚Ä¶', 3591),
 ('because', 3396),
 ('tax', 3396),
 ('you!', 3381),
 ('fight', 3248),
 ('district', 3204),
 ('her', 3146),
 ('back', 3139),
 ('right', 3125),
 ('american', 3124),
 ('those', 3096),
 ('going', 3093),
 ('house', 3064),
 ('everyone', 3061),
 ('a‚Ä¶', 3041),
 ('state', 3014),
 ('please', 3009),
 ('much', 2972),
 ('stand', 2942),
 ('running', 2917),
 ('president', 2880),
 ('keep', 2822),
 ('come', 2809),
 ('go', 2796),
 ('honored', 2772),
 ('meet', 2758),
 ('against', 2709),
 ('country', 2702),
 ('the‚Ä¶', 2700),
 ('voters', 2693),
 ('being', 2683),
 ('another', 2665),
 ('team', 2642),
 ('love', 2606),
 ('@realdonaldtrump', 2589),
 ('families', 2582),
 ('sure', 2572),
 ('were', 2569),
 ('she', 2542),
 ('big', 2494),
 ('after', 2487),
 ('always', 2468),
 ('still', 2443),
 ('very', 2438),
 ('election', 2425),
 ('to‚Ä¶', 2417),
 ('candidate', 2416),
 ('across', 2369),
 ('way', 2358),
 ('stop', 2355),
 ('community', 2352),
 ('days', 2346),
 ('most', 2344),
 ('into', 2320),
 ('family', 2310),
 ('health', 2306),
 ('you,', 2306),
 ('hard', 2302),
 ('republican', 2297),
 ('while', 2278),
 ('don‚Äôt', 2247),
 ('where', 2245),
 ('them', 2238),
 ('years', 2236),
 ('meeting', 2235),
 ('too', 2220),
 ('never', 2216),
 ('morning', 2192),
 ('forward', 2186),
 ('public', 2163),
 ('important', 2145),
 ('talk', 2115),
 ('americans', 2111),
 ("we're", 2088),
 ('gun', 2083),
 ('honor', 2074),
 ('talking', 2061),
 ('even', 2060),
 ('republicans', 2051),
 ('night', 2042),
 ('democratic', 2035),
 ('care', 2026),
 ('ready', 2021),
 ('tonight', 2019),
 ("don't", 2014),
 ('next', 2006),
 ('democrats', 2006),
 ('got', 2004),
 ('children', 1980),
 ('th‚Ä¶', 1978),
 ('school', 1974),
 ('today.', 1965),
 ('any', 1960),
 ('year', 1955),
 ('made', 1954),
 ('think', 1952),
 ('today,', 1913),
 ('friends', 1894),
 ('better', 1894),
 ('looking', 1881),
 ('check', 1877),
 ('hope', 1875),
 ('protect', 1869),
 ('national', 1860),
 ('change', 1854),
 ('believe', 1852),
 ('i‚Ä¶', 1841),
 ('off', 1836),
 ('congressional', 1834),
 ('look', 1832),
 ('gop', 1830),
 ('town', 1829),
 ('until', 1826),
 ('did', 1823),
 ('put', 1817),
 ('we‚Äôre', 1813),
 ('local', 1807),
 ('party', 1805),
 ('say', 1801),
 ('may', 1797),
 ('having', 1784),
 ('money', 1781),
 ('let‚Äôs', 1759),
 ('best', 1753),
 ('live', 1747),
 ("let's", 1745),
 ('also', 1745),
 ('other', 1740),
 ('let', 1733),
 ('fighting', 1732),
 ('getting', 1723),
 ('endorsement', 1717),
 ('making', 1717),
 ('week', 1711),
 ('before', 1709),
 ('janice', 1707),
 ('down', 1705),
 ('which', 1700),
 ('sign', 1690),
 ('voting', 1683),
 ('students', 1683),
 ('could', 1680),
 ('part', 1671),
 ('office', 1670),
 ('excited', 1668),
 ('two', 1656),
 ('volunteers', 1652),
 ('and‚Ä¶', 1647),
 ('healthcare', 1640),
 ('voted', 1631),
 ('amazing', 1625),
 ('bill', 1617),
 ('needs', 1613),
 ('win', 1612),
 ('government', 1602),
 ('said', 1577),
 ('folks', 1575),
 ('continue', 1569),
 ('w‚Ä¶', 1566),
 ('you.', 1554),
 ('young', 1542),
 ('america', 1536),
 ('since', 1529),
 ('today!', 1529),
 ('rep.', 1523),
 ('show', 1522),
 ('candidates', 1520),
 ('de', 1520),
 ('together', 1517),
 ('event', 1515),
 ('coming', 1514),
 ('leaders', 1511),
 ('hear', 1485),
 ('o‚Ä¶', 1477),
 ('primary', 1476),
 ('remember', 1474),
 ('came', 1467),
 ('special', 1464),
 ('give', 1461),
 ('call', 1460),
 ('it.', 1453),
 ('end', 1445),
 ('find', 1443),
 ('‚Äî', 1441),
 ('real', 1438),
 ('doing', 1428),
 ('news', 1413),
 ('bring', 1411),
 ('wonderful', 1399),
 ('u.s.', 1391),
 ('tomorrow', 1387),
 ('pay', 1384),
 ('2018', 1383),
 ('speak', 1381),
 ('support!', 1378),
 ('him', 1377),
 ('members', 1352),
 ("can't", 1350),
 ('jobs', 1349),
 ('opponent', 1347),
 ('s‚Ä¶', 1342),
 ('does', 1339),
 ('high', 1321),
 ('in‚Ä¶', 1315),
 ('issues', 1310),
 ('congratulations', 1307),
 ('c‚Ä¶', 1304),
 ('long', 1303),
 ('taking', 1303),
 ('washington', 1299),
 ('‚Äì', 1297),
 ('then', 1289),
 ('--', 1288),
 ('can‚Äôt', 1285),
 ('through', 1284),
 ('deserve', 1274),
 ('political', 1264),
 ('away', 1264),
 ('doors', 1260),
 ('its', 1253),
 ('really', 1251),
 ('opportunity', 1233),
 ('federal', 1228),
 ('open', 1228),
 ('such', 1225),
 ('arnold-jones', 1221),
 ('that‚Äôs', 1214),
 ('strong', 1209),
 ('endorsed', 1208),
 ('early', 1203),
 ('administration', 1202),
 ('read', 1196),
 ('hall', 1194),
 ('lives', 1188),
 ('city', 1184),
 ('enjoyed', 1182),
 ('law', 1178),
 ('left', 1177),
 ('fair', 1172),
 ('few', 1170),
 ('life', 1165),
 ('glad', 1164),
 ('f‚Ä¶', 1163),
 ('economy', 1163),
 ('grateful', 1160),
 ('future', 1152),
 ('former', 1151),
 ('own', 1144),
 ('beautiful', 1144),
 ('of‚Ä¶', 1139),
 ('speaking', 1136),
 ('small', 1136),
 ('weekend', 1130),
 ('without', 1129),
 ('rights', 1129),
 ('run', 1118),
 ('congressman', 1118),
 ('share', 1118),
 ('leadership', 1110),
 ('someone', 1107),
 ('attack', 1104),
 ('yesterday', 1102),
 ('social', 1091),
 ('job', 1088),
 ('friend', 1088),
 ('plan', 1086),
 ('access', 1086),
 ("that's", 1082),
 ('act', 1071),
 ('lot', 1070),
 ('around', 1070),
 ('nm', 1070),
 ('home', 1069),
 ('united', 1067),
 ('texas', 1064),
 ('full', 1059),
 ('incredible', 1058),
 ('during', 1056),
 ("i'll", 1049),
 ('i‚Äôll', 1044),
 ('things', 1040),
 ('again', 1040),
 ('annual', 1039),
 ('under', 1035),
 ('world', 1032),
 ('dr.', 1032),
 ('tell', 1028),
 ('celebrate', 1028),
 ('north', 1028),
 ('veterans', 1027),
 ('both', 1026),
 ('well', 1025),
 ('for‚Ä¶', 1022),
 ('i‚Äôve', 1016),
 ('h‚Ä¶', 1014),
 ('men', 1012),
 ('education', 1011),
 ('register', 1009),
 ('service', 1009),
 ('knocking', 1008),
 ('security', 1006),
 ('day!', 1006),
 ('watch', 1005),
 ('business', 1005),
 ('same', 1004),
 ('spent', 1001),
 ('race', 999),
 ('start', 998),
 ('million', 998),
 ('kids', 989),
 ('parade', 989),
 ("i've", 985),
 ('debate', 983),
 ('action', 981),
 ("you're", 976),
 ('voice', 976),
 ('you‚Äôre', 973),
 ('agree', 972),
 ('cuts', 970),
 ('via', 966),
 ('hosting', 966),
 ('appreciate', 964),
 ('means', 963),
 ('policy', 961),
 ('already', 952),
 ('economic', 948),
 ('send', 948),
 ('states', 943),
 ('workers', 943),
 ('elected', 943),
 ('immigration', 942),
 ('2', 941),
 ('march', 926),
 ('supporters', 926),
 ('group', 924),
 ('done', 922),
 ('corporate', 921),
 ('senate', 917),
 ('seeing', 913),
 ('p‚Ä¶', 908),
 ('little', 908),
 ('nation', 906),
 ('met', 906),
 ('thing', 905),
 ('visit', 903),
 ('free', 901),
 ('john', 901),
 ('labor', 899),
 ('joined', 892),
 ('enough', 890),
 ('an‚Ä¶', 888),
 ('this.', 886),
 ('wants', 885),
 ('ever', 884),
 ('learn', 884),
 ('supporting', 880),
 ('receive', 879),
 ('november', 879),
 ('power', 875),
 ('use', 873),
 ('something', 872),
 ('nothing', 868),
 ('yet', 866),
 ('m‚Ä¶', 865),
 ('b‚Ä¶', 862),
 ('military', 860),
 ('june', 860),
 ('volunteer', 859),
 ('congress,', 858),
 ('country.', 857),
 ('paul', 855),
 ('congress.', 854),
 ('trying', 852),
 ('energy', 848),
 ('fun', 844),
 ('day.', 842),
 ('huge', 840),
 ('says', 839),
 ('lost', 836),
 ('polls', 836),
 ('phone', 835),
 ('teachers', 835),
 ('place', 835),
 ('message', 831),
 ('violence', 828),
 ('voter', 828),
 ('helping', 828),
 ('standing', 821),
 ('thousands', 821),
 ('celebrating', 818),
 ('heard', 813),
 ('each', 808),
 ('senator', 805),
 ('able', 803),
 ('justice', 801),
 ('evening', 797),
 ('less', 796),
 ('discuss', 796),
 ('communities', 789),
 ('saturday', 786),
 ('@gop', 786),
 ('1', 781),
 ('3', 781),
 ('fellow', 780),
 ('took', 779),
 ('day,', 779),
 ('history', 775),
 ('cut', 775),
 ('past', 775),
 ('safe', 775),
 ('cannot', 774),
 ('joining', 774),
 ('common', 772),
 ('funding', 772),
 ('d‚Ä¶', 771),
 ('west', 769),
 ('true', 768),
 ('war', 766),
 ('represent', 765),
 ('ask', 759),
 ('anyone', 757),
 ('la', 757),
 ('ago', 756),
 ('district.', 752),
 ('affordable', 751),
 ('tune', 751),
 ('grassroots', 747),
 ('afraid', 745),
 ('spending', 742),
 ('he‚Äôs', 742),
 ('once', 740),
 ('forum', 740),
 ('.', 739),
 ('support.', 739),
 ('spend', 737),
 ('makes', 736),
 ('joe', 735),
 ('serve', 733),
 ('person', 732),
 ('me.', 731),
 ("doesn't", 730),
 ('court', 730),
 ('afternoon', 730),
 ('campaign.', 728),
 ('representative', 727),
 ('birthday', 724),
 ("here's", 721),
 ('kind', 721),
 ('white', 720),
 ('actually', 719),
 ('system', 719),
 ('signs', 717),
 ('feel', 717),
 ("we've", 715),
 ('elections', 715),
 ('forget', 715),
 ('old', 714),
 ('democracy', 714),
 ('chance', 714),
 ('passed', 712),
 ('ensure', 712),
 ('record', 707),
 ('matter', 707),
 ('supreme', 706),
 ('clear', 703),
 ('policies', 702),
 ('politics', 701),
 ('everything', 700),
 ('maxine', 700),
 ('hey', 699),
 ('stay', 697),
 ('between', 695),
 ('truly', 694),
 ('sense', 693),
 ('follow', 691),
 ('top', 689),
 ('hold', 688),
 ('man', 686),
 ('step', 685),
 ('member', 684),
 ('welcome', 683),
 ('flip', 683),
 ('yes', 679),
 ('legislation', 678),
 ('story', 678),
 ('we‚Ä¶', 678),
 ('dems', 676),
 ('democrat', 675),
 ('r‚Ä¶', 675),
 ('far', 672),
 ('reform', 671),
 ('border', 671),
 ('we‚Äôve', 671),
 ('farmers', 671),
 ('listen', 670),
 ('1st', 668),
 ('worked', 664),
 ('w/', 664),
 ('protecting', 663),
 ('waters', 662),
 ('!', 662),
 ('looks', 661),
 ('including', 661),
 ('seen', 657),
 ('called', 657),
 ('college', 657),
 ('@potus', 657),
 ('congrats', 657),
 ('elect', 655),
 ('doesn‚Äôt', 655),
 ('calling', 653),
 ('donate', 651),
 ('three', 650),
 ('5', 647),
 ('us.', 645),
 ("won't", 645),
 ('bad', 644),
 ('yard', 643),
 ('pass', 642),
 ('4', 642),
 ('woman', 641),
 ('citizens', 639),
 ('video', 638),
 ('gave', 636),
 ('millions', 636),
 ('@aynrandpaulryan', 636),
 ('here:', 633),
 ('co‚Ä¶', 632),
 ('instead', 632),
 ('trump‚Äôs', 631),
 ("isn't", 630),
 ('blue', 630),
 ('turnout', 630),
 ('awesome', 629),
 ('fundraising', 629),
 ('tonight.', 629),
 ('our‚Ä¶', 628),
 ('leader', 626),
 ('trade', 625),
 ('putting', 625),
 ('told', 624),
 ('turn', 624),
 ('continues', 623),
 ('rally', 622),
 ('words', 621),
 ("trump's", 620),
 ('issue', 620),
 ('announce', 618),
 ('human', 617),
 ('interview', 617),
 ('questions', 617),
 ('south', 617),
 ('it!', 616),
 ('ballot', 615),
 ('received', 613),
 ('wait', 611),
 ('facebook', 611),
 ('people.', 609),
 ('food', 609),
 ('pleasure', 609),
 ('middle', 608),
 ('tonight!', 607),
 ('thoughts', 606),
 ('committed', 606),
 ('isn‚Äôt', 605),
 ('heart', 605),
 ('medicare', 603),
 ('donald', 602),
 ('held', 602),
 ('vote.', 602),
 ('kavanaugh', 600),
 ("he's", 600),
 ('class', 599),
 ('single', 598),
 ('started', 597),
 ('por', 597),
 ("today's", 596),
 ('hours', 593),
 ('10', 591),
 ('clean', 590),
 ('conversation', 587),
 ('vote!', 587),
 ('asked', 582),
 ('is‚Ä¶', 582),
 ('now.', 581),
 ('address', 581),
 ('raise', 580),
 ('union', 579),
 ('committee', 576),
 ('schools', 575),
 ('almost', 575),
 ('knock', 574),
 ('decision', 574),
 ('l‚Ä¶', 573),
 ('e‚Ä¶', 573),
 ('opioid', 573),
 ('greet', 573),
 ('6', 572),
 ('opening', 572),
 ('parents', 571),
 ('families.', 571),
 ('went', 569),
 ('politicians', 569),
 ('black', 567),
 ('especially', 566),
 ('morning.', 566),
 ('door', 566),
 ('stopped', 565),
 ('month', 565),
 ('california', 563),
 ('second', 563),
 ('comes', 562),
 ('businesses', 562),
 ('climate', 562),
 ('giving', 560),
 ('statement', 559),
 ('now,', 559),
 ('current', 558),
 ('paid', 557),
 ('on‚Ä¶', 556),
 ('july', 556),
 ('yes,', 555),
 ('center', 555),
 ('support,', 555),
 ('hearing', 554),
 ('today‚Äôs', 553),
 ('won‚Äôt', 553),
 ('child', 552),
 ('week,', 552),
 ('safety', 550),
 ('rural', 549),
 ('build', 548),
 ('critical', 546),
 ('central', 545),
 ('night.', 545),
 ('you‚Ä¶', 544),
 ('shows', 543),
 ('fo‚Ä¶', 538),
 ('fantastic', 538),
 ('nearly', 537),
 ('set', 536),
 ("we'll", 536),
 ('g‚Ä¶', 536),
 ('living', 536),
 ('face', 536),
 ('deadline', 535),
 ('used', 535),
 ('st.', 534),
 ('values', 534),
 ("women's", 533),
 ('red', 532),
 ('reason', 532),
 ('didn‚Äôt', 532),
 ('fired', 531),
 ('constituents', 529),
 ('calls', 529),
 ('arnold-jones,', 529),
 ('months', 528),
 ('paying', 527),
 ('4th', 527),
 ('thanks,', 526),
 ('events', 525),
 ('progressive', 524),
 ('create', 523),
 ('y‚Ä¶', 523),
 ('signed', 522),
 ('here‚Äôs', 521),
 ('leading', 521),
 ('visiting', 521),
 ('icymi:', 521),
 ('lead', 520),
 ('companies', 520),
 ('moment', 520),
 ('helped', 520),
 ('y', 520),
 ('club', 519),
 ('absolutely', 518),
 ('times', 517),
 ('student', 517),
 ('mayor', 517),
 ('understand', 516),
 ('canvassing', 516),
 ('neighbors', 515),
 ('number', 514),
 ('them.', 512),
 ('loved', 512),
 ('corporations', 512),
 ('sunday', 511),
 ('taxes', 511),
 ('poll', 510),
 ('seat', 510),
 ('freedom', 510),
 ('üá∫üá∏', 510),
 ('nice', 510),
 ('line', 509),
 ('latest', 508),
 ('weeks', 507),
 ('thrilled', 507),
 ('saying', 506),
 ('behind', 506),
 ('growing', 505),
 ('bipartisan', 505),
 ('reminder', 504),
 ('2nd', 504),
 ('anniversary', 504),
 ('water', 503),
 ('showing', 500),
 ('knows', 500),
 ('farm', 499),
 ('budget', 499),
 ('close', 498),
 ('mr.', 498),
 ('god', 498),
 ('rest', 497),
 ('move', 497),
 ('august', 496),
 ('saw', 496),
 ('taken', 496),
 ('wish', 494),
 ('become', 494),
 ('#bluewave', 494),
 ('up.', 491),
 ('there‚Äôs', 491),
 ('answer', 490),
 ('twitter', 490),
 ('letter', 490),
 ('served', 490),
 ('el', 489),
 ('dedicated', 489),
 ('general', 489),
 ('festival', 488),
 ('residents', 488),
 ('takes', 488),
 ('entire', 487),
 ('conservative', 486),
 ('favorite', 486),
 ('#ad', 486),
 ('listening', 485),
 ('steve', 485),
 ('prayers', 485),
 ('park', 484),
 ('‚Äúthe', 483),
 ('women‚Äôs', 483),
 ('try', 482),
 ('starting', 481),
 ('deserves', 481),
 ('wishing', 480),
 ('scott', 480),
 ('judge', 480),
 ('supports', 480),
 ('throughout', 478),
 ('building', 478),
 ('ryan', 477),
 ('sharing', 476),
 ('votes', 476),
 ('order', 476),
 ('mark', 476),
 ('n‚Ä¶', 475),
 ('movement', 475),
 ('lots', 475),
 ('question', 473),
 ('drug', 473),
 ('voices', 473),
 ('ice', 473),
 ('at‚Ä¶', 472),
 ('walk', 471),
 ('cost', 471),
 ('officials', 471),
 ('that‚Ä¶', 469),
 ('fought', 469),
 ('we‚Äôll', 468),
 ('"the', 468),
 ('tour', 468),
 ('hit', 467),
 ('spoke', 467),
 ('word', 467),
 ('"i', 467),
 ('week.', 467),
 ('be‚Ä¶', 467),
 ('email', 467),
 ('polling', 467),
 ('media', 466),
 ('me,', 464),
 ('keeping', 464),
 ('earned', 464),
 ('block', 463),
 ('ago,', 463),
 ('election.', 462),
 ('save', 462),
 ('thankful', 462),
 ('post', 462),
 ('mike', 461),
 ("didn't", 460),
 ('brave', 460),
 ('100', 459),
 ('asking', 459),
 ('along', 458),
 ('demand', 458),
 ('billion', 457),
 ('attend', 457),
 ('governor', 457),
 ('king', 456),
 ('dc', 454),
 ('efforts', 453),
 ('exactly', 453),
 ('point', 451),
 ('recent', 451),
 ("there's", 451),
 ('crowd', 450),
 ('year.', 449),
 ('allow', 449),
 ('provide', 448),
 ('happening', 447),
 ('bringing', 447),
 ('people,', 446),
 ('thanks!', 445),
 ('year,', 445),
 ('night!', 445),
 ('with‚Ä¶', 445),
 ('#bluewave2018', 444),
 ('major', 443),
 ('inspired', 442),
 ('valley', 441),
 ('link', 440),
 ('@momsdemand', 440),
 ('hundreds', 440),
 ('crisis', 440),
 ('directly,', 440),
 ('article', 439),
 ('name', 439),
 ('discussion', 438),
 ('registered', 437),
 ('problem', 437),
 ('7', 437),
 ('whether', 437),
 ('involved', 436),
 ('career', 436),
 ('wages', 436),
 ('gets', 435),
 ('fire', 435),
 ('what‚Äôs', 435),
 ('medical', 434),
 ('ad', 434),
 ('trillion', 433),
 ('time.', 433),
 ('sexual', 432),
 ('spread', 432),
 ('powerful', 431),
 ('county.', 431),
 ('goes', 431),
 ('due', 430),
 ('here.', 429),
 ('miss', 428),
 ('much!', 428),
 ('others', 428),
 ('roger', 428),
 ('commitment', 427),
 ('equal', 426),
 ('anything', 426),
 ('@betoorourke', 426),
 ('serving', 426),
 ('using', 425),
 ('walking', 425),
 ('humbled', 424),
 ('attended', 423),
 ('victory', 423),
 ('community.', 423),
 ('inspiring', 422),
 ('en', 422),
 ('friday', 421),
 ('morning!', 421),
 ('key', 420),
 ('yesterday.', 420),
 ('right.', 419),
 ('mean', 418),
 ('example', 417),
 ('reach', 417),
 ('works', 417),
 ('won', 416),
 ('infrastructure', 416),
 ('8', 416),
 ('immigrants', 415),
 ('this‚Ä¶', 415),
 ('enjoy', 414),
 ('starts', 414),
 ('thought', 414),
 ('experience', 412),
 ('program', 411),
 ('virginia', 411),
 ('finally', 410),
 ...]

In [66]:
words_df = pd.DataFrame(Counter(" ".join(tweet_df.text).lower().split()).most_common())

In [67]:
words_df.columns = ['word','counts']

In [68]:
words_df.head()

  word  counts
0  the  150035
1   to  134224
2  and   76218
3    a   67296
4   in   65462

In [69]:
words_df.to_csv('common_words.csv',index=False)

In [88]:
len(words_df)

428499

In [70]:
words_df[words_df.word.str.contains('#')].to_csv('hashtag.csv',index=False)

## Frequent words by party

### Democratic party

In [74]:
df_dem = tweet_df[tweet_df.party == 'Democratic'].reset_index(drop=True)

In [76]:
dem_words = pd.DataFrame(Counter(" ".join(df_dem.text).lower().split()).most_common())

In [78]:
dem_words.columns = ['word','counts']

In [86]:
dem_words[dem_words.word.str.contains('#')].head(10)

                   word  counts
626           #bluewave     490
694       #bluewave2018     443
826         #goptaxscam     371
1014  #marchforourlives     298
1017          #fliptx14     297
1160              #va07     261
1212     #netneutrality     249
1227              #gotv     245
1244    #teamspanberger     241
1525              #sotu     190

### Republican party

In [82]:
df_rep = tweet_df[tweet_df.party == 'Republican'].reset_index(drop=True)

In [83]:
rep_words = pd.DataFrame(Counter(" ".join(df_rep.text).lower().split()).most_common())

In [84]:
rep_words.columns = ['word','counts']

In [87]:
rep_words[rep_words.word.str.contains('#')].head(10)

              word  counts
210            #ad     486
348          #maga     312
382    #republican     290
429          #ny21     250
495           #abq     218
505           #unm     212
523  #voteburchett     205
553          #az01     192
628      #indagent     173
629    #mbamortage     173